general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle

    col.active_border = rgb(d91e36)
    col.inactive_border = rgb(3a3a3a)
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = false
    }
}

animations {
    enabled = yes

    bezier = snap, 0.15, 0.95, 0.05, 1.0
    bezier = fast, 0.20, 0.90, 0.10, 1.0

    animation = windows, 1, 2, snap, slide
    animation = windowsIn, 1, 2, snap, slide
    animation = windowsOut, 1, 1, fast, slide
    animation = windowsMove, 1, 1, fast
    animation = fade, 1, 1, fast
    animation = border, 1, 1, fast
    animation = workspaces, 1, 2, snap, slidefade 8%
    animation = specialWorkspace, 1, 2, snap, slidefade 8%
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

windowrule = match:class .*, rounding 0

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
